#!/bin/bash

function rand(){
    min=$1
    max=$(($2-$min+1))
    num=$(cat /dev/urandom | head -n 10 | cksum | awk -F ' ' '{print $1}')
    echo $(($num%$max+$min))
}

rnd=$(rand 2 254)

ip addr add 10.1.1.$rnd/24 dev usb0
ip dev usb0 up
